export const VGC_ITEMS = [
  "",
  "Sitrus Berry",
  "Safety Goggles",
  "Focus Sash",
  "Assault Vest",
  "Life Orb",
  "Choice Band",
  "Choice Specs",
  "Choice Scarf",
  "Leftovers",
  "Rocky Helmet",
  "Covert Cloak",
  "Clear Amulet",
  "Mental Herb",
  "Power Herb",
  "White Herb",
  "Eject Button",
  "Eject Pack",
  "Red Card",
  "Iron Ball",
  "Flame Orb",
  "Toxic Orb",
  "Booster Energy",
  "Weakness Policy",
  "Air Balloon",
  "Expert Belt",
  "Muscle Band",
  "Wise Glasses",
  "Scope Lens",
  "Bright Powder",
  "Lum Berry",
  "Chesto Berry",
  "Wiki Berry",
  "Iapapa Berry",
  "Figy Berry",
  "Mago Berry",
  "Aguav Berry",
  "Occa Berry",
  "Passho Berry",
  "Wacan Berry",
  "Rindo Berry",
  "Yache Berry",
  "Chople Berry",
  "Kebia Berry",
  "Shuca Berry",
  "Coba Berry",
  "Payapa Berry",
  "Tanga Berry",
  "Charti Berry",
  "Kasib Berry",
  "Haban Berry",
  "Colbur Berry",
  "Babiri Berry",
  "Chilan Berry",
  "Roseli Berry",
];

export const VGC_NATURES = [
  "",
  "Hardy",
  "Lonely",
  "Brave",
  "Adamant",
  "Naughty",
  "Bold",
  "Docile",
  "Relaxed",
  "Impish",
  "Lax",
  "Timid",
  "Hasty",
  "Serious",
  "Jolly",
  "Naive",
  "Modest",
  "Mild",
  "Quiet",
  "Bashful",
  "Rash",
  "Calm",
  "Gentle",
  "Sassy",
  "Careful",
  "Quirky",
];

export const TERA_TYPES = [
  "",
  "Normal",
  "Fire",
  "Water",
  "Electric",
  "Grass",
  "Ice",
  "Fighting",
  "Poison",
  "Ground",
  "Flying",
  "Psychic",
  "Bug",
  "Rock",
  "Ghost",
  "Dragon",
  "Dark",
  "Steel",
  "Fairy",
  "Stellar",
];
